---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml
    - vars/guacamole.yml

  roles:
    - image-name
    - default-user
    - setup
    - xfce4-desktop
    - common
    - guacamole
    - openstack-clients
    - transcribemydata
    - config
    - testing
    - nectar-user
    - facts
    - cleanup
